services:
  spring-boot-app:
    build: .
    restart: always
    ports:
      - 9090:8080
      - 9096:8086
    environment:
      MYSQL_HOST: db-mysql
      MYSQL_PORT: 3306
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: secret
    depends_on:
      - db-mysql

  db-mysql:
    image: "mysql:latest"
    restart: always
    ports: 
      - 23306:3306
    environment:
      MYSQL_DATABASE: formula1
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
