services:
  api:
    build: .
    restart: always
    ports:
      - 9090:8080
      - 9096:8086
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_mysql:3306/formula1?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      db_mysql:
        condition: service_healthy
    command: >
      sh -c "until nc -z db_mysql 3306; do echo waiting for mysql; sleep 2; done; java -jar app.jar"

  db_mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: formula1
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3316:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
